name: 'Docs'

on:
  workflow_dispatch:
  push:
    branches: ['master']

jobs:
  docs:
    name: 'Docs'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.zensical.outputs.page_url }}

    steps:
      - name: 'Zensical Action'
        id: zensical
        uses: cssnr/zensical-action@v1.0.7

# name: Publish docs via GitHub Pages
#on:
 # push:
 #   branches:
 #     - master

#jobs:
#  build:
#    name: Deploy docs
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout master
#        uses: actions/checkout@v1

      #- name: Deploy docs
      #  uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #  env:
       #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


       
